version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - ccamel
      - fredericvilcot
      - amimart
    assignees:
      - ccamel
      - fredericvilcot
      - amimart
    open-pull-requests-limit: 5
