branches:
  - main
repositoryUrl: "git@github.com:axone-protocol/ontology.git"
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Axone Ontology Changelog"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files: [version]
          from: ^.+$
          to: ${nextRelease.version}
          countMatches: true
          results:
            - file: version
              hasChanged: true
              numMatches: 1
              numReplacements: 1
  - - "@semantic-release/exec"
    - prepareCmd: make build
  - - "@semantic-release/exec"
    - prepareCmd: make docs
  - - "@semantic-release/github"
    - successComment: false
      assets:
        - label: Axone Ontology (Turtle)
          path: ./target/axone-ontology-*.ttl
        - label: Axone Ontology (RDF/XML)
          path: ./target/axone-ontology-*.rdf.xml
        - label: Axone Ontology (N-Triples)
          path: ./target/axone-ontology-*.nt
        - label: Axone Ontology Bundle
          path: ./target/axone-ontology-*-bundle.tar.gz
  - - "@semantic-release/git"
    - assets:
        - docs/schemas/*.md
        - CHANGELOG.md
        - version
      message: "chore(release): perform release ${nextRelease.version}"
