name: Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_call:

  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build documentation
        run: |
          make documentation
