name: Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_call:

  workflow_dispatch:

jobs:
  build-ontology:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build ontology and examples
        run: |
          make build
