name: Build / Ontology

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-ontology.yml'
      - 'src/**'
      - 'script/**'
      - 'LICENSE'
      - 'Makefile'
      - 'flake.lock'
      - 'flake.nix'
      - 'version'

  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/build-ontology.yml'
      - 'src/**'
      - 'script/**'
      - 'LICENSE'
      - 'Makefile'
      - 'version'
      - 'flake.lock'
      - 'flake.nix'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ontology:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22


      - name: Build ontology and examples
        run: nix develop --command make build
