name: Checks

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  commits-are-conventional:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commits
        uses: wagoid/commitlint-github-action@v4

  ontology-is-valid:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - run: |
          gem install rdf-turtle

      - name: Validate ontology file
        run: |
          rdf validate --validate src/okp4.ttl