name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  commits-are-conventional:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commits
        uses: wagoid/commitlint-github-action@v4