name: Lint / Nix

on:
  push:
    branches: [main]
    paths:
      - '.envrc'
      - '.github/workflows/lint-nix.yml'
      - 'flake.lock'
      - 'flake.nix'
      - '**/*.nix'

  pull_request:
    branches: [main]
    paths:
      - '.envrc'
      - '.github/workflows/lint-nix.yml'
      - 'flake.lock'
      - 'flake.nix'
      - '**/*.nix'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-nix:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Check flake
        run: nix flake check --all-systems --show-trace --print-build-logs

      - name: Check formatting
        run: |
          mapfile -t nix_files < <(git ls-files '*.nix')
          nix develop --command nixfmt --check "${nix_files[@]}"

      - name: Statix
        run: nix develop --command statix check .

      - name: Deadnix
        run: nix develop --command deadnix --fail .
