name: notify-release

on:
  release:
    types: [published]

jobs:
  update-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Update ontology docs repository
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.github.com/repos/axone-protocol/docs/actions/workflows/39152549/dispatches'
          method: 'POST'
          customHeaders: '{"Accept": "application/vnd.github+json", "Authorization": "Bearer ${{ secrets.OPS_TOKEN }}"}'
          data: |-
            {
              "ref": "main",
              "inputs": {
                "version": "${{ github.event.release.tag_name }}",
                "repository": "${{github.repository}}",
                "section": "ontology",
                "docs_directory": "docs/*"
              }
            }
