name: Publish

on:
  push:
    tags: [ "v*" ]

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-gh-pages:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build documentation
        run: |
          make documentation

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: replace release version in index.html
        run: sed -i 's/{{release_version}}/${{ steps.get_version.outputs.version }}/' .github/gh-home/index.html
        id: update-version-home-page

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github/gh-home/
          keep_files: true
          commit-message: |
            chore: update redirection to latest version (auto)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/generated/ontology/
          destination_dir: versions/${{ steps.get_version.outputs.version }}
          keep_files: true
          commit-message: |
            chore: release ontology github pages ${{ steps.get_version.outputs.version }}
          cname: ontology.okp4.network
