name: Publish
"on":
  push:
    branches:
      - main
    tags:
      - v*
concurrency:
  group: "publish-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  publish-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Bump version to next (if not tagged)
        if: "startsWith(github.ref, 'refs/heads/')"
        run: |
          echo next > version

      - name: Build ontology
        run: |
          make build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.OKP4_TOKEN }}
          publish_dir: target/ontology/
          destination_dir: .
          keep_files: true
          cname: ontology.okp4.space
