name: Publish

on:
  push:
    branches: [main]
    tags: [ "v*" ]

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-gh-pages:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build documentation
        run: |
          make documentation

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/
          exclude_assets: okp4.ttl
          keep_files: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/generated/ontology/
          destination_dir: versions/${{ steps.get_version.outputs.version }}
          keep_files: true
          cname: ontology.okp4.network
